stages:
  - e2e

e2e-tests:
  stage: e2e
  image: node:22
  tags: []
  script:
    - apt-get update && apt-get install -y curl
    - if ! command -v yarn > /dev/null; then npm install -g yarn; fi
    - yarn
    - yarn playwright install
    - yarn playwright install-deps
    - yarn run e2e
  when: manual
  allow_failure: false
