# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome da 'pipeline'
name: 'Execução Manual'

# regras de disparo (triggers/ gatilhos)
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:

# trabalhos/tarefas dentro da pipeline = jobs
jobs:
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do proejto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação de dependencias
      - name: Instalando dependencias
        run: yarn

      # instalação do Playwright
      - name: Instalando o playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e
